### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by hernanwilkinson** [ba-st/Chalten#4]
When evaluating: 
Metacello new
    baseline: 'Chalten';
    githubUser: 'ba-st' project: 'chalten' commitish: 'v6.0.0' path: 'repository';
    load

It does not load. See attached screenshot
<img width="940" alt="screen shot 2018-11-07 at 15 35 44" src="https://user-images.githubusercontent.com/58615/48152491-d6bba080-e2a2-11e8-822a-18d024b8a6a6.png">

**Comment by gcotelli** [comment]
Pharo version?

**Comment by hernanwilkinson** [comment]
Pharo 6.0
Latest update: #60543

**Comment by hernanwilkinson** [comment]
Update it to Pharo 6.0
Latest update: #60546
And same problem

**Comment by gcotelli** [comment]
I've tried in a pristine Pharo 6.0 / Latest update: #60546 image on Linux and it worked.
I've downloaded it with `curl https://get.pharo.org/61+vm | bash` , open the image and run your code.
